version: '3.8'

networks:
  my-cron-network:
    external: false
    name: my-cron-network
    driver: bridge

services:
  my_cron_job:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: crone_tab_external
    environment:
      - APP_SUPER_SECRET=${APP_SUPER_SECRET}
    volumes:
      - ./cron.log:/var/log/cron.log
    networks:
      - my-cron-network
